language: php
php:
  - 5.4
before_script:
  # For the syntax check to work we need some fake vars
  - mkdir /home/travis/build/Miraheze/private                -Needs to be changed, Reception123
  - cp /home/travis/build/Miraheze/mw-config/.travis.vars.yml /home/travis/build/Miraheze/private/vars.yml  -^, reception123

script:
  # Check playbook syntax
  - sudo mw-config -i production local.yml --syntax-check
  # Check php script syntax
  - bash .travis.phplint.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
    on_success: change
    on_failure: always
