language: php
php:
  - 5.5
  - 5.6
  - hhvm

script:
  # Check php script syntax
  - bash .travis.phplint.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
      - reviwiki@gmail.com
    on_success: change
    on_failure: always
